### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by FerdinandoPucci** [fiji/register_virtual_stack_slices#11]
This is actually not an issue with the macro call (see my other issue report), it happens when RVSS is manually started.

java.lang.NullPointerException
	at register_virtual_stack.Register_Virtual_Stack_MT.exec(Register_Virtual_Stack_MT.java:1235)
	at register_virtual_stack.Register_Virtual_Stack_MT.exec(Register_Virtual_Stack_MT.java:422)
	at register_virtual_stack.Register_Virtual_Stack_MT.exec(Register_Virtual_Stack_MT.java:334)
	at register_virtual_stack.Register_Virtual_Stack_MT.run(Register_Virtual_Stack_MT.java:289)
	at ij.IJ.runUserPlugIn(IJ.java:235)
	at ij.IJ.runPlugIn(IJ.java:198)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)

Fiji 1.53c
Java 1.8.0_172 (64-bit)

**Comment by iarganda** [comment]
Thanks for reporting @FerdinandoPucci. Can you tell me the steps you took? What are the parameters you chose?

**Comment by FerdinandoPucci** [comment]
Thanks @iarganda for following up.  Unfortunately I do not have the details of that command anymore, but the good news is that it did not happen again.
