### ISSUE TITLE
Error "Wrong dimensions of stack"  when using TIF 16 bits as source images

### ISSUE THREAD

**Issue by racagalro** [fiji/register_virtual_stack_slices#9]
I'm trying to register 4 TIF uncompressed 16 bits images. The reference image is loaded ok but when loading slice 2 the following exception appears on console:
java.lang.IllegalArgumentException: Wrong dimensions for this stack
	at ij.ImagePlus.setProcessor(ImagePlus.java:617)
	at register_virtual_stack.Register_Virtual_Stack_MT.register(Register_Virtual_Stack_MT.java:1863)
	at If I try the same with same four images but register_virtual_stack.Register_Virtual_Stack_MT.exec(Register_Virtual_Stack_MT.java:1238)
	at register_virtual_stack.Register_Virtual_Stack_MT.exec(Register_Virtual_Stack_MT.java:421)
	at register_virtual_stack.Register_Virtual_Stack_MT.exec(Register_Virtual_Stack_MT.java:333)
	at register_virtual_stack.Register_Virtual_Stack_MT.run(Register_Virtual_Stack_MT.java:288)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)

In debug mode, the following messages are write in log:
windowActivated: Registered tif_1920
setKeyUp: -1
runPlugIn: register_virtual_stack.Register_Virtual_Stack_MT
actionPerformed: time=1592322219649, java.awt.event.ActionEvent[ACTION_PERFORMED,cmd=Register Virtual Stack Slices,when=1592322219647,modifiers=] on menuitem0
runUserPlugIn: register_virtual_stack.Register_Virtual_Stack_MT, arg=
GenericDialog font: false java.awt.Font[family=Dialog,name=Dialog,style=plain,size=12]
windowActivated: Registered tif_1920
focusGained: img["Registered tif_1920" (-85), 24-bit, 4913x3215x1x4x1]
openImage: "tif", /home/rafa/fotos/prueba_fiji/TIF_16bits/DSC_0859.tif
windowActivated: Registered tif_1920
focusGained: img["Registered tif_1920" (-85), 24-bit, 4913x3215x1x4x1]

  DSC_0859.tif: opening
    256, "ImageWidth", value=4310
    257, "ImageLength", value=2868
    258, "BitsPerSample", value=218, count=3
    259, "Compression", value=1
    262, "PhotoInterp", value=2
    266, "???", value=1
    273, "StripOffsets", value=224, count=2868
    277, "SamplesPerPixel", value=3
    278, "RowsPerStrip", value=1
    279, "StripByteCount", value=11696, count=2868
    282, "XResolution", value=23168
    283, "YResolution", value=23176
    284, "PlanarConfiguration", value=1
    296, "ResolutionUnit", value=2
    339, "SampleFormat", value=23184, count=3
    700, "???", value=23190, count=2558
    34675, "???", value=25748, count=9044
  nextIFD=0
number of IFDs: 1
offset to first image: 34792
gap between images: 0
little-endian byte order: true
 
FileInfo: name=DSC_0859.tif, dir=/home/rafa/fotos/prueba_fiji/TIF_16bits/, width=4310, height=2868, nImages=1, offset=34792, gap=0, type=RGB48, byteOrder=little, format=2, url=, whiteIsZero=f, lutSize=0, comp=1, ranges=null, samples=3
stack.viewers: 1
CompositeImage: img["DSC_0859.tif" (-89), 16-bit, 4310x2868x3x1x1] 1 3
stack.viewers: 2
openImage: "tif", /home/rafa/fotos/prueba_fiji/TIF_16bits/DSC_0860.tif

  DSC_0860.tif: opening
    256, "ImageWidth", value=4310
    257, "ImageLength", value=2868
    258, "BitsPerSample", value=218, count=3
    259, "Compression", value=1
    262, "PhotoInterp", value=2
    266, "???", value=1
    273, "StripOffsets", value=224, count=2868
    277, "SamplesPerPixel", value=3
    278, "RowsPerStrip", value=1
    279, "StripByteCount", value=11696, count=2868
    282, "XResolution", value=23168
    283, "YResolution", value=23176
    284, "PlanarConfiguration", value=1
    296, "ResolutionUnit", value=2
    339, "SampleFormat", value=23184, count=3
    700, "???", value=23190, count=2558
    34675, "???", value=25748, count=9044
  nextIFD=0
number of IFDs: 1
offset to first image: 34792
gap between images: 0
little-endian byte order: true
 
FileInfo: name=DSC_0860.tif, dir=/home/rafa/fotos/prueba_fiji/TIF_16bits/, width=4310, height=2868, nImages=1, offset=34792, gap=0, type=RGB48, byteOrder=little, format=2, url=, whiteIsZero=f, lutSize=0, comp=1, ranges=null, samples=3
stack.viewers: 1
CompositeImage: img["DSC_0860.tif" (-94), 16-bit, 4310x2868x3x1x1] 1 3
stack.viewers: 2
err >java.lang.IllegalArgumentException: Wrong dimensions for this stack
err >	at ij.ImagePlus.setProcessor(ImagePlus.java:617)
err >	at register_virtual_stack.Register_Virtual_Stack_MT.register(Register_Virtual_Stack_MT.java:1863)
err >	at register_virtual_stack.Register_Virtual_Stack_MT.exec(Register_Virtual_Stack_MT.java:1238)
err >	at register_virtual_stack.Register_Virtual_Stack_MT.exec(Register_Virtual_Stack_MT.java:421)
err >	at register_virtual_stack.Register_Virtual_Stack_MT.exec(Register_Virtual_Stack_MT.java:333)
err >	at register_virtual_stack.Register_Virtual_Stack_MT.run(Register_Virtual_Stack_MT.java:288)
err >	at ij.IJ.runUserPlugIn(IJ.java:230)
err >	at ij.IJ.runPlugIn(IJ.java:193)
err >	at ij.Executer.runCommand(Executer.java:137)
err >	at ij.Executer.run(Executer.java:66)
err >	at java.lang.Thread.run(Thread.java:748)
setKeyUp: -1
setKeyUp: 18
setKeyDown: 18
keyPressed: code=18 (Alt), char="￿" (65535), flags=Alt
setKeyUp: 18
setKeyDown: 18
keyPressed: code=18 (Alt), char="￿" (65535), flags=Alt
setKeyUp: 18
actionPerformed: time=1592322435423, java.awt.event.ActionEvent[ACTION_PERFORMED,cmd=Register Virtual Stack Slices,when=1592322435422,modifiers=] on menuitem0
runPlugIn: register_virtual_stack.Register_Virtual_Stack_MT
runUserPlugIn: register_virtual_stack.Register_Virtual_Stack_MT, arg=
GenericDialog font: false java.awt.Font[family=Dialog,name=Dialog,style=plain,size=12]
windowActivated: Registered tif_1920
focusGained: img["Registered tif_1920" (-85), 24-bit, 4913x3215x1x4x1]
openImage: "tif", /home/rafa/fotos/prueba_fiji/TIF_32bits/DSC_0859.tif
windowActivated: Registered tif_1920
focusGained: img["Registered tif_1920" (-85), 24-bit, 4913x3215x1x4x1]
err >java.lang.NullPointerException
err >	at register_virtual_stack.Register_Virtual_Stack_MT.exec(Register_Virtual_Stack_MT.java:1204)
err >	at register_virtual_stack.Register_Virtual_Stack_MT.exec(Register_Virtual_Stack_MTIf I try the same with same four images but .java:421)
err >	at register_virtual_stack.Register_Virtual_Stack_MT.exec(Register_Virtual_Stack_MT.java:333)
err >	at register_virtual_stack.Register_Virtual_Stack_MT.run(Register_Virtual_Stack_MT.java:288)
err >	at ij.IJ.runUserPlugIn(IJ.java:230)
err >	at ij.IJ.runPlugIn(IJ.java:193)
err >	at ij.Executer.runCommand(Executer.java:137)
err >	at ij.Executer.run(Executer.java:66)
err >	at java.lang.Thread.run(Thread.java:748)

If I use TIF 8bits uncompressed images as input, I have no problem. My version of ImageJ is 1.52p. I don't know the version of Registration plugin but it must be the last one because I had updated all plugins before testing.

**Comment by iarganda** [comment]
Sorry for the late answer, @racagalro I tried reproducing the error but it works fine on my machine. Did you figure out if it was a problem with your images?
